name: Create Pull Request
on:
  schedule:
    - cron: '0 9 * * 4'
  push:
    branches:
      - develop
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - uses: peter-evans/create-pull-request@v3.6.0
        with:
          token: ${{ secrets.PAT }}
          title: Promote develop to stage
          commit-message: Merges develop branch into stage branch
          branch: develop
