name: Create Pull Request
on:
  schedule:
    - cron: '0 9 * * 4'
  push:
    branches:
      - develop
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT }}
          source_branch: develop
          destination_branch: stage
          pr_title: Promote develop to stage
